version: '3.4'

services:
  terraglamp:

    image: terraglamp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8888:8888

  caddy:
    image: caddy:2-alpine
    command: ["caddy", "reverse-proxy", "--from", "test-terraglamp.duckdns.org", "--to", "terraglamp:8888"]
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  mongodb:

    image: mongo
    container_name: mongodb
    ports:
      - 2717:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      
  mongo-express:

    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
