version: '3.4'

services:
  terraglamp:

    image: terraglamp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - $API_PORT:$API_PORT
    env_file:
      - .env

  caddy:
    image: caddy:2-alpine
    build: 
      context: .
      dockerfile: ./caddy/Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/public:/app/frontend/public:ro
      - ./frontend/dist:/app/frontend/dist:ro

  mongodb:

    image: mongo
    container_name: mongodb
    ports:
      - $MONGO_PORT:27017
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
    env_file:
      - .env
      
  mongo-express:

    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASS
      - ME_CONFIG_MONGODB_SERVER=mongodb
    env_file:
      - .env
